name: Check Markdown links

on: [push, pull_request] 
  schedule: cron "0 9 * * 1" #Run the action every Monday at 9 am.

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1